package mcp

import (
	"slices"
	"strings"
	"testing"

	"github.com/runos-official/cli/internal/manifest"
)

// buildKitSetAdvancedConfigsCommand returns the conductor manifest entry
// for services/buildkit/{id}/set-advanced-configs (MANIFEST_VERSION
// 28.24.0, objective 60 story 108) as the MCP server sees it. The tool
// is generated by the generic manifest-driven path (no shim), so this
// fixture pins that a conductor-side schema change can't silently break
// the MCP write tool's shape.
//
// Field shape matches the house set-advanced-configs pattern, confirmed
// across all five deployed sibling commands (postgresql, prometheus,
// litellm, traefik, vllm): the enum select fields (snapshotter, logLevel,
// logFormat) carry a STRUCTURED Enum array (postgresql + vllm do the
// same), while DEFAULTS live in the description PROSE, never as a
// structured `default` field (zero of the five structures a default).
// So the projected MCP tool surfaces enums as JSON Schema constraints and
// defaults as readable description text. Field types and the camelCase
// wire names match the conductor schema (story 108).
func buildKitSetAdvancedConfigsCommand() manifest.Command {
	return manifest.Command{
		Command:     "services/buildkit/{id}/set-advanced-configs",
		Description: "Set BuildKit advanced configuration (GC, parallelism, history, worker, logging).",
		Endpoint:    "/:aid/:cid/services/buildkit/:id/set-advanced-configs",
		Method:      "POST",
		MCP:         []string{"write"},
		Input: &manifest.Input{Fields: []manifest.Field{
			{Name: "id", Type: "string", Required: true, Positional: true},
			{Name: "gc", Type: "boolean", Description: "Enable garbage collection (default: true)."},
			{Name: "gcMaxUsedSpaceGb", Type: "integer", Description: "Max cache disk usage in GB (default: 5, 1-10000)."},
			{Name: "gcReservedSpaceGb", Type: "integer", Description: "Reserved cache space in GB (default: 1, 0-10000)."},
			{Name: "gcMinFreeSpaceGb", Type: "integer", Description: "Min free disk to keep in GB (default: 2, 0-10000)."},
			{Name: "gcKeepDurationShortH", Type: "integer", Description: "Short GC policy keep duration in hours (default: 48, 1-8760)."},
			{Name: "gcKeepBytesShortGb", Type: "integer", Description: "Short GC policy keep bytes in GB (default: 1, 0-10000)."},
			{Name: "gcKeepDurationLongH", Type: "integer", Description: "Long GC policy keep duration in hours (default: 168, 1-8760)."},
			{Name: "gcKeepBytesLongGb", Type: "integer", Description: "Long GC policy keep bytes in GB (default: 2, 0-10000)."},
			{Name: "buildMaxParallelism", Type: "integer", Description: "Max parallel build steps (default: 4, 1-256)."},
			{Name: "cniPoolSize", Type: "integer", Description: "CNI network namespace pool size (default: 16, 0-1024)."},
			{Name: "historyMaxAgeS", Type: "integer", Description: "Build history max age in seconds (default: 172800, 0-31536000)."},
			{Name: "historyMaxEntries", Type: "integer", Description: "Build history max entries (default: 50, 0-100000)."},
			{Name: "platforms", Type: "string", Description: "Comma-separated multi-arch target list (default: empty = auto-detect)."},
			{Name: "snapshotter", Type: "string", Enum: []string{"auto", "overlayfs", "native"}, Description: "Worker snapshotter (default: auto). Changing it discards build cache."},
			{Name: "logLevel", Type: "string", Enum: []string{"error", "warn", "info", "debug", "trace"}, Description: "Daemon log level (default: info)."},
			{Name: "logFormat", Type: "string", Enum: []string{"text", "json"}, Description: "Daemon log format (default: text)."},
			{Name: "platformsCacheMaxAgeS", Type: "integer", Description: "Platforms cache max age in seconds (default: 3600, 0-31536000)."},
		}},
		Output: &manifest.Output{Type: "object", Fields: []manifest.OutputField{{Name: "jobId"}}},
	}
}

func findTool(tools []Tool, name string) *Tool {
	for i := range tools {
		if tools[i].Name == name {
			return &tools[i]
		}
	}
	return nil
}

// TestBuildKitSetAdvancedConfigsMCPTool pins the MCP write-tool shape the
// generic manifest path produces for the BuildKit advanced-config
// command: correct tool name, cid + every field as a property, id
// required, integer->number type mapping, and enum/default surfaced on
// the fields that carry them. This is the MCP half of story 110.
func TestBuildKitSetAdvancedConfigsMCPTool(t *testing.T) {
	s := &Server{
		manifest: &manifest.Manifest{Commands: []manifest.Command{buildKitSetAdvancedConfigsCommand()}},
		version:  "test",
		category: "write",
	}
	tools := s.buildTools()

	// Tool name maps only `/`->`_`; hyphens in the leaf verb survive, so
	// the name is services_buildkit_set-advanced-configs (NOT ..._set_
	// advanced_configs). Pin it so the conductor MCP shim / docs that
	// reference this exact string stay in sync.
	tool := findTool(tools, "services_buildkit_set-advanced-configs")
	if tool == nil {
		t.Fatal("services_buildkit_set-advanced-configs tool not generated under the write category")
	}

	props := tool.InputSchema.Properties

	// cid is injected because the endpoint carries :cid.
	if _, ok := props["cid"]; !ok {
		t.Error("cid property missing (endpoint has :cid)")
	}

	// Every manifest field surfaces as a property under its camelCase
	// wire name (NOT the kebab CLI flag form).
	wantNumberFields := []string{
		"gcMaxUsedSpaceGb", "gcReservedSpaceGb", "gcMinFreeSpaceGb",
		"gcKeepDurationShortH", "gcKeepBytesShortGb", "gcKeepDurationLongH",
		"gcKeepBytesLongGb", "buildMaxParallelism", "cniPoolSize",
		"historyMaxAgeS", "historyMaxEntries", "platformsCacheMaxAgeS",
	}
	for _, name := range wantNumberFields {
		p, ok := props[name]
		if !ok {
			t.Errorf("property %q missing", name)
			continue
		}
		// integer -> number in JSON Schema.
		if p.Type != "number" {
			t.Errorf("property %q type = %q, want number", name, p.Type)
		}
	}

	// gc toggle projects as boolean; its default lives in the description
	// prose (house pattern), not a structured JSON Schema default.
	if p := props["gc"]; p.Type != "boolean" {
		t.Errorf("gc type = %q, want boolean", p.Type)
	} else if !strings.Contains(p.Description, "default: true") {
		t.Errorf("gc description = %q, want it to surface the prose default", p.Description)
	}

	// id is required and string-typed.
	if p := props["id"]; p.Type != "string" {
		t.Errorf("id type = %q, want string", p.Type)
	}
	if !slices.Contains(tool.InputSchema.Required, "id") {
		t.Errorf("id not marked required; required = %v", tool.InputSchema.Required)
	}

	// Enum fields surface their structured options so the LLM picks a
	// valid value instead of guessing.
	enumCases := map[string][]string{
		"snapshotter": {"auto", "overlayfs", "native"},
		"logLevel":    {"error", "warn", "info", "debug", "trace"},
		"logFormat":   {"text", "json"},
	}
	for name, want := range enumCases {
		p, ok := props[name]
		if !ok {
			t.Errorf("enum field %q missing", name)
			continue
		}
		if p.Type != "string" {
			t.Errorf("enum field %q type = %q, want string", name, p.Type)
		}
		if len(p.Enum) != len(want) {
			t.Errorf("enum field %q options = %v, want %v", name, p.Enum, want)
			continue
		}
		for i := range want {
			if p.Enum[i] != want[i] {
				t.Errorf("enum field %q option[%d] = %q, want %q", name, i, p.Enum[i], want[i])
			}
		}
	}
}
