package output

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/runos-official/cli/internal/manifest"
)

// Objective 93, story 217.
//
// The objective's operator criterion is that a dependent service's status
// names WHICH backing service is at fault, and names it the way the operator
// knows it. This file is the CLI's half of the proof: that an ENRICHED status
// payload reaches the operator through the generic renderer without losing a
// key, and that the one place the renderer did lose keys is fixed.
//
// Everything here is evidence class "unit test against recorded payloads".
// No backend is probed, no health verdict is formed, and none of the
// objective's reproduction criteria are claimed: those need the lab and a
// real no-usable-drives backend and belong to the conductor stories.

// statusSetPath is the checked-in, generated set of every manifest command
// that returns a service status read (criterion 1). Generated by
// scripts/status_command_set.py; see testdata/status/PROVENANCE.md.
const statusSetPath = "../../testdata/status"

type statusCommand struct {
	Command      string   `json:"command"`
	Endpoint     string   `json:"endpoint"`
	OutputType   string   `json:"output_type"`
	OutputFields []string `json:"output_fields"`
}

type statusCommandSet struct {
	ManifestVersion string          `json:"manifest_version"`
	Source          string          `json:"source"`
	Count           int             `json:"count"`
	Commands        []statusCommand `json:"commands"`
}

func loadStatusCommandSet(t *testing.T) statusCommandSet {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(statusSetPath, "status-commands.json"))
	if err != nil {
		t.Fatalf("read status command set: %v", err)
	}
	var set statusCommandSet
	if err := json.Unmarshal(raw, &set); err != nil {
		t.Fatalf("parse status command set: %v", err)
	}
	if len(set.Commands) == 0 {
		t.Fatal("status command set is empty; re-run scripts/status_command_set.py")
	}
	if set.Count != len(set.Commands) {
		t.Fatalf("set count %d disagrees with %d recorded commands", set.Count, len(set.Commands))
	}
	return set
}

// enrichedFixtures are the three payload shapes conductor may plausibly
// choose, recorded in testdata/status/fixtures. Returned as raw bytes,
// because criterion 5 asserts byte identity against these exact bytes.
func enrichedFixtures(t *testing.T) map[string][]byte {
	t.Helper()
	dir := filepath.Join(statusSetPath, "fixtures")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixture dir: %v", err)
	}
	out := map[string][]byte{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			t.Fatalf("read fixture %s: %v", e.Name(), err)
		}
		out[e.Name()] = raw
	}
	if len(out) != 3 {
		t.Fatalf("expected the 3 recorded enriched payloads, found %d", len(out))
	}
	return out
}

// TestStatusCommandSet_OutputTypeCensus pins the measured shape of the set,
// so criterion 3's "array-typed or type-unset" bucket being EMPTY is a
// checked-in fact rather than a step nobody ran. When a future manifest adds
// a status read that is not object-typed, this fails and points at the sweep
// that must be extended instead of letting the entry go unexercised.
func TestStatusCommandSet_OutputTypeCensus(t *testing.T) {
	set := loadStatusCommandSet(t)

	census := map[string]int{}
	var notObject []string
	for _, c := range set.Commands {
		key := c.OutputType
		if key == "" {
			key = "<unset>"
		}
		census[key]++
		if c.OutputType != "object" {
			notObject = append(notObject, fmt.Sprintf("%s (%s)", c.Command, key))
		}
	}
	t.Logf("manifest %s, %d status reads, output types: %v", set.ManifestVersion, len(set.Commands), census)

	if len(notObject) > 0 {
		t.Fatalf("the set now carries %d non-object status reads: %v\n"+
			"Criterion 3 requires each to be exercised and its rendering outcome recorded. "+
			"Extend TestEnrichedStatusRendersLosslessly's list-shaped branch and update "+
			"testdata/status/PROVENANCE.md.", len(notObject), notObject)
	}

	// The cluster deployment-readiness reader is in the set by name, not by
	// the path rule, so assert it explicitly: it is the reader that reported
	// ready during the incident.
	found := false
	for _, c := range set.Commands {
		if c.Command == "clusters/is-app-deployment-ready" {
			found = true
		}
	}
	if !found {
		t.Error("cluster deployment-readiness command missing from the set")
	}
}

// TestEnrichedStatusRendersLosslessly is criterion 2 (and criterion 3 for any
// non-object entry that appears later). For EVERY entry in the generated set
// it feeds each enriched payload through the renderer with that command's
// declared output fields, and asserts every key and every value survives into
// the plain-text output.
func TestEnrichedStatusRendersLosslessly(t *testing.T) {
	set := loadStatusCommandSet(t)
	fixtures := enrichedFixtures(t)

	for _, cmd := range set.Commands {
		for name, body := range fixtures {
			t.Run(cmd.Command+"/"+name, func(t *testing.T) {
				var payload map[string]any
				if err := json.Unmarshal(body, &payload); err != nil {
					t.Fatalf("parse fixture: %v", err)
				}

				out := renderWithDeclaredFields(t, cmd, body)

				for _, key := range collectKeys(payload) {
					// Sub-table column headers are upper-cased by the
					// renderer, so key presence is matched case-insensitively.
					if !strings.Contains(strings.ToLower(out), strings.ToLower(key)) {
						t.Errorf("key %q lost from output:\n%s", key, out)
					}
				}
				for _, val := range collectScalars(payload) {
					if !strings.Contains(out, val) {
						t.Errorf("value %q lost from output:\n%s", val, out)
					}
				}
			})
		}
	}
}

// TestEnrichedStatusNamesTheFailingBackend is the operator criterion stated
// as its own assertion: the failing backing service's NAME and TYPE, which
// are what an operator recognises, must be readable in the plain text of
// every status read in the set.
func TestEnrichedStatusNamesTheFailingBackend(t *testing.T) {
	set := loadStatusCommandSet(t)
	fixtures := enrichedFixtures(t)

	const (
		backendName = "images-object-store"
		backendType = "minio"
	)

	for _, cmd := range set.Commands {
		for name, body := range fixtures {
			out := renderWithDeclaredFields(t, cmd, body)
			if !strings.Contains(out, backendName) {
				t.Errorf("%s/%s: failing backend NAME %q absent:\n%s", cmd.Command, name, backendName, out)
			}
			if !strings.Contains(out, backendType) {
				t.Errorf("%s/%s: failing backend TYPE %q absent:\n%s", cmd.Command, name, backendType, out)
			}
		}
	}
}

// renderWithDeclaredFields renders body the way the CLI would for cmd: as an
// object when the manifest declares an object, and otherwise through the
// list-shaped (table) path with the payload as a single row, which is the
// surface the nested-object summary defect lived on.
func renderWithDeclaredFields(t *testing.T, cmd statusCommand, body []byte) string {
	t.Helper()
	fields := make([]manifest.OutputField, 0, len(cmd.OutputFields))
	for _, f := range cmd.OutputFields {
		fields = append(fields, manifest.OutputField{Name: f})
	}
	def := &manifest.Output{Type: cmd.OutputType, Fields: fields}

	data := body
	if cmd.OutputType != "object" {
		// A list-shaped read renders one row per item, so wrap the recorded
		// payload as that single row.
		data = append(append([]byte("["), body...), ']')
		if def.Type == "" {
			def.Type = "array"
		}
	}
	return captureStdout(t, func() {
		if err := NewFormatter(false).Format(data, def); err != nil {
			t.Fatalf("format: %v", err)
		}
	})
}

// collectKeys returns every key name anywhere in the payload.
func collectKeys(v any) []string {
	seen := map[string]bool{}
	var walk func(any)
	walk = func(v any) {
		switch t := v.(type) {
		case map[string]any:
			for k, inner := range t {
				seen[k] = true
				walk(inner)
			}
		case []any:
			for _, inner := range t {
				walk(inner)
			}
		}
	}
	walk(v)
	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// collectScalars returns every scalar value anywhere in the payload, rendered
// the way the formatter renders it, so the assertions compare like with like.
func collectScalars(v any) []string {
	seen := map[string]bool{}
	var walk func(any)
	walk = func(v any) {
		switch t := v.(type) {
		case map[string]any:
			for _, inner := range t {
				walk(inner)
			}
		case []any:
			for _, inner := range t {
				walk(inner)
			}
		default:
			if s := formatValue(t); s != "" {
				seen[s] = true
			}
		}
	}
	walk(v)
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

// TestNestedStatusObject_KeepsKeysBeyondTheSummary is criterion 4, and it is
// the defect this story exists to fix. A status sub-object in a TABLE CELL
// that carries the failing backend's name, type or reason beside its state
// used to collapse to the state (and the message), discarding the very
// attribution the objective requires.
func TestNestedStatusObject_KeepsKeysBeyondTheSummary(t *testing.T) {
	cases := []struct {
		name string
		obj  map[string]any
		want []string
	}{
		{
			name: "backend attribution beside the state",
			obj: map[string]any{
				"state":       "unhealthy",
				"message":     "a recorded backing service cannot serve",
				"backendName": "images-object-store",
				"backendType": "minio",
			},
			want: []string{"backendName=images-object-store", "backendType=minio", "state=unhealthy"},
		},
		{
			name: "reason beside the state, no message",
			obj: map[string]any{
				"state":  "unhealthy",
				"reason": "no usable drives",
			},
			want: []string{"reason=no usable drives", "state=unhealthy"},
		},
		{
			name: "fault domain separates own fault from backend fault",
			obj: map[string]any{
				"state":       "unhealthy",
				"message":     "deployment has no ready replica",
				"faultDomain": "self",
			},
			want: []string{"faultDomain=self", "message=deployment has no ready replica", "state=unhealthy"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatNestedObject(tc.obj, 0)
			for _, want := range tc.want {
				if !strings.Contains(got, want) {
					t.Errorf("rendered cell %q is missing %q", got, want)
				}
			}
			// And nothing at all is dropped.
			for k := range tc.obj {
				if !strings.Contains(got, k) {
					t.Errorf("key %q discarded from cell %q", k, got)
				}
			}
		})
	}
}

// TestNestedObjectDefaultBranch_Ordering pins the lead-key rule the rework
// added. An object that carries a summary pattern's trigger key renders that
// pattern's keys first, so a narrow column keeps the value it is named for;
// an object that carries no trigger key keeps the plain alphabetical order it
// had before this story touched the branch.
func TestNestedObjectDefaultBranch_Ordering(t *testing.T) {
	cases := []struct {
		name string
		obj  map[string]any
		want string
	}{
		{
			name: "state leads, message second, remainder alphabetised",
			obj: map[string]any{
				"reason":      "no usable drives",
				"message":     "cannot serve",
				"state":       "unhealthy",
				"backendName": "images-object-store",
			},
			want: "state=unhealthy, message=cannot serve, backendName=images-object-store, reason=no usable drives",
		},
		{
			name: "state leads even with no message",
			obj:  map[string]any{"backendType": "minio", "state": "degraded"},
			want: "state=degraded, backendType=minio",
		},
		{
			name: "link pattern leads name then link",
			obj:  map[string]any{"type": "ingress", "link": "https://example.com", "name": "web"},
			want: "name=web, link=https://example.com, type=ingress",
		},
		{
			name: "replicas pattern leads desired, ready, available",
			obj:  map[string]any{"updated": 3.0, "available": 2.0, "desired": 3.0, "ready": 2.0},
			want: "desired=3, ready=2, available=2, updated=3",
		},
		{
			// Review finding, rework cycle 2. The pre-fix replicas branch
			// returned only when `ready` AND `available` were both present,
			// so a partial replicas object always reached the default branch
			// and always rendered alphabetically. The lead must not widen
			// that set, or the story's "no existing rendering moves" claim
			// stops being literally true.
			name: "partial replicas object keeps the plain alphabetical order",
			obj:  map[string]any{"desired": 3.0, "available": 2.0},
			want: "available=2, desired=3",
		},
		{
			name: "partial replicas object with an unrelated key stays alphabetical",
			obj:  map[string]any{"desired": 3.0, "appName": "x"},
			want: "appName=x, desired=3",
		},
		{
			name: "no trigger key keeps the plain alphabetical order",
			obj:  map[string]any{"zeta": "z", "alpha": "a", "name": "n"},
			want: "alpha=a, name=n, zeta=z",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := formatNestedObject(tc.obj, 0); got != tc.want {
				t.Errorf("got  %q\nwant %q", got, tc.want)
			}
		})
	}
}

// TestNestedStatusObject_ContainedShapesRenderUnchanged is criterion 4's
// companion: an object the summary already described IN FULL must render
// byte-identically to the pre-change build. The want strings below were
// captured from the build at HEAD before the containment gate landed, not
// recalled.
func TestNestedStatusObject_ContainedShapesRenderUnchanged(t *testing.T) {
	cases := []struct {
		obj  map[string]any
		want string
	}{
		{map[string]any{"state": "healthy"}, "healthy"},
		{map[string]any{"state": "unhealthy", "message": "pod not ready"}, "unhealthy (pod not ready)"},
		{map[string]any{"state": "unhealthy", "message": ""}, "unhealthy"},
		{map[string]any{"link": "https://example.com", "name": "web"}, "web: https://example.com"},
		{map[string]any{"link": "https://example.com"}, "https://example.com"},
		{map[string]any{"desired": 3.0, "ready": 2.0, "available": 2.0}, "2/3 ready, 2 available"},
	}
	for _, tc := range cases {
		if got := formatNestedObject(tc.obj, 0); got != tc.want {
			t.Errorf("rendering moved: got %q, want %q (obj %v)", got, tc.want, tc.obj)
		}
	}
}

// TestExistingRealPayloadShapesRenderUnchanged guards the risk the plan named
// for the containment gate: that a REAL payload carrying `link` or `replicas`
// with extra keys would have its rendering moved. Both shapes below are the
// live ones — `apps/network-access` rows ({type,name,link}, typed in
// internal/deploy as NetworkAccess) and the `replicas` block
// ({desired,ready,available}, per the service status handbook articles) — and
// both want strings were captured from the pre-change build.
func TestExistingRealPayloadShapesRenderUnchanged(t *testing.T) {
	networkAccess := []byte(`[{"type":"ingress","name":"web","link":"https://web.example.com"}]`)
	got := captureStdout(t, func() {
		_ = NewFormatter(false).Format(networkAccess, &manifest.Output{Type: "array", Fields: []manifest.OutputField{
			{Name: "type"}, {Name: "name"}, {Name: "link"},
		}})
	})
	want := "TYPE     NAME  LINK                     \n" +
		"----------------------------------------\n" +
		"ingress  web   https://web.example.com  \n"
	if got != want {
		t.Errorf("apps/network-access rendering moved:\ngot:\n%s\nwant:\n%s", got, want)
	}

	show := []byte(`{"id":"ab12c","replicas":{"desired":3,"ready":2,"available":2},` +
		`"networkAccess":[{"type":"ingress","name":"web","link":"https://web.example.com"}]}`)
	got = captureStdout(t, func() {
		_ = NewFormatter(false).Format(show, &manifest.Output{Type: "object", Fields: []manifest.OutputField{
			{Name: "id"}, {Name: "replicas"}, {Name: "networkAccess"},
		}})
	})
	want = "id           : ab12c\n" +
		"replicas     :\n" +
		"  available: 2\n" +
		"  desired  : 3\n" +
		"  ready    : 2\n" +
		"networkAccess: 1 entry\n" +
		"  LINK                     NAME  TYPE\n" +
		"  ----------------------------------------\n" +
		"  https://web.example.com  web   ingress\n"
	if got != want {
		t.Errorf("apps/show rendering moved:\ngot:\n%s\nwant:\n%s", got, want)
	}

	list := []byte(`[{"id":"ab12c","state":{"state":"healthy"},"replicas":{"desired":3,"ready":2,"available":2}}]`)
	got = captureStdout(t, func() {
		_ = NewFormatter(false).Format(list, &manifest.Output{Type: "array", Fields: []manifest.OutputField{
			{Name: "id"}, {Name: "state"}, {Name: "replicas"},
		}})
	})
	want = "ID     STATE    REPLICAS                \n" +
		"----------------------------------------\n" +
		"ab12c  healthy  2/3 ready, 2 available  \n"
	if got != want {
		t.Errorf("list-shaped status rendering moved:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// TestListShapedStatusRendering is the list-shaped surface, where the
// enriched status column meets the table's pre-existing 40-rune per-cell
// cap. THE STATE WORD MUST SURVIVE THAT CAP. Review finding, rework cycle 1:
// the first cut of this fix let the default branch emit keys in pure
// alphabetical order, so `state` sorted behind `backendName`, `message` and
// `reason` and the cap cut the cell before it. The column named STATE then
// carried no state at all, which inverts the objective's operator criterion
// on exactly the surface this story set out to repair. The default branch
// now leads with the keys the summary patterns consume, so the verdict is
// never the thing that gets elided.
//
// No manifest status read is list-shaped today (see the census test), so
// this exercises the real top-level array path against synthetic rows.
func TestListShapedStatusRendering(t *testing.T) {
	cases := []struct {
		name string
		body string
		// wantVisible must appear in the rendered cell.
		wantVisible []string
		// elided names what the 40-rune cap cuts for this row. Recorded,
		// not tolerated silently: --json carries the full value, and the
		// object-shaped surface every manifest status read declares has no
		// such cap.
		elided []string
	}{
		{
			name:        "backend attribution beside the state",
			body:        `[{"id":"ab12c","state":{"state":"unhealthy","backendName":"images-object-store","backendType":"minio"}}]`,
			wantVisible: []string{"state=unhealthy", "backendName=images-"},
			elided:      []string{"backendType=minio"},
		},
		{
			name:        "message and reason beside the state",
			body:        `[{"id":"ab12c","state":{"state":"unhealthy","message":"a backing service cannot serve","reason":"no usable drives"}}]`,
			wantVisible: []string{"state=unhealthy", "message=a backing"},
			elided:      []string{"reason=no usable drives"},
		},
		{
			name:        "short attribution fits whole",
			body:        `[{"id":"ab12c","state":{"state":"unhealthy","reason":"no drives"}}]`,
			wantVisible: []string{"state=unhealthy", "reason=no drives"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			out := captureStdout(t, func() {
				_ = NewFormatter(false).Format([]byte(tc.body), &manifest.Output{Type: "array", Fields: []manifest.OutputField{
					{Name: "id"}, {Name: "state"},
				}})
			})
			t.Logf("rendered:\n%s", out)

			// The health verdict is never what the cap cuts.
			if !strings.Contains(out, "unhealthy") {
				t.Errorf("the STATE column lost the state word entirely:\n%s", out)
			}
			for _, want := range tc.wantVisible {
				if !strings.Contains(out, want) {
					t.Errorf("expected %q in the cell:\n%s", want, out)
				}
			}
			for _, gone := range tc.elided {
				if strings.Contains(out, gone) {
					t.Logf("NOTE: %q now fits; the recorded elision list is stale, tighten it", gone)
				}
			}
			if len(tc.elided) > 0 && !strings.Contains(out, "...") {
				t.Errorf("expected the 40-rune cap to elide the tail:\n%s", out)
			}
		})
	}
}

// TestJSONOutputByteIdenticalToBody is criterion 5: the text-mode work did not
// touch the machine-readable path. Each fixture is stored in Go's canonical
// MarshalIndent form (see PROVENANCE.md), so the assertion is literal byte
// identity against the recorded response body, plus a structural round-trip
// check that survives any future re-indentation of the fixtures.
func TestJSONOutputByteIdenticalToBody(t *testing.T) {
	fixtures := enrichedFixtures(t)

	// The criterion-4 cell payloads too, so every payload in criteria 2-4 is
	// covered.
	fixtures["cell/backend-attribution"] = []byte("{\n  \"backendName\": \"images-object-store\",\n" +
		"  \"backendType\": \"minio\",\n  \"message\": \"a recorded backing service cannot serve\",\n" +
		"  \"state\": \"unhealthy\"\n}\n")
	fixtures["cell/contained-status"] = []byte("{\n  \"message\": \"pod not ready\",\n  \"state\": \"unhealthy\"\n}\n")

	for name, body := range fixtures {
		t.Run(name, func(t *testing.T) {
			out := captureStdout(t, func() {
				if err := NewFormatter(true).Format(body, &manifest.Output{Type: "object"}); err != nil {
					t.Fatalf("format json: %v", err)
				}
			})
			if out != string(body) {
				t.Errorf("--json output is not byte-identical to the body:\ngot:\n%q\nwant:\n%q", out, string(body))
			}
			var gotV, wantV any
			if err := json.Unmarshal([]byte(out), &gotV); err != nil {
				t.Fatalf("json output does not parse: %v", err)
			}
			if err := json.Unmarshal(body, &wantV); err != nil {
				t.Fatalf("body does not parse: %v", err)
			}
			if fmt.Sprintf("%v", gotV) != fmt.Sprintf("%v", wantV) {
				t.Errorf("json round-trip differs:\ngot  %v\nwant %v", gotV, wantV)
			}
		})
	}
}
